### ISSUE TITLE
Remover imagem docker do package registry

### ISSUE THREAD

**Issue by dehmirandac2** [b2wads/firebolt#27]
Adicionamos uma imagem docker no package registry do Github. Precisamos ver como removê-la.
Alguns links que podem ser úteis:

https://developer.github.com/v4/input_object/deletepackageversioninput/
https://developer.github.com/v4/guides/forming-calls/
https://developer.github.com/v4/previews/#access-to-package-version-deletion

**Comment by apfzvd** [comment]
Acho que foi feito, né?
